### ISSUE TITLE
String Keys Are Not Preserved

### ISSUE THREAD

**Issue by bnert** [dvingo/cljs-emotion#9]
Hello!

Quick issue I ran into. Not sure if it is specific to the version I am using (2021-03-10.0.0).

I am declaring a style like so:
```clojure
(defstyled full-height :div
  {:height "100%"}
  (fn [props]
    (:style props)))

# In a component in a different file
(defn some-component []
  [component {:style {:width "70%"
                      "@media (min-width: 700px)" {:width "50%"}}}
    [:p "hello"]])
```

I am expecting that the string media query will be preserved, however, it is not and transformed into a keyword, which causes issues when rendering a component.

Is this expected behavior?

Let me know if you have any follow up questions!

Note: I have found a workaround for now, but this functionality would be nice. Would be up for submitting a patch when I have time. 🙂

**Comment by dvingo** [comment]
Hi thanks for the report! I recently was playing around with adding support for passing keywords as values to the props of the handler function (they were getting transformed into strings) and I think it broke this functionality. The nested media queries are definitely supposed to work. I'll take a look at fixing it :)

**Comment by dvingo** [comment]
Just pushed up a fix for this. Thanks again for reporting it. Here's a working example:
https://dvingo.github.io/cljs-emotion/#!/dv.cljs_emotion.reagent_debug 
Let me know if you run into anything else!

**Comment by dvingo** [comment]
Just an FYI - if you use `:style` as a prop to your function, that will end up being passed to the react component created by emotion which will attempt to set the `:style` react property, so I would recommend renaming it to something else, like `:styles` or `:css`.
Emotion will filter out non-html props before passing them react, it happens here if you're curious:

https://github.com/emotion-js/emotion/blob/d25316393639232df16ba836b407e3678eea5e4d/packages/styled/src/utils.js#L46

https://github.com/emotion-js/emotion/blob/d25316393639232df16ba836b407e3678eea5e4d/packages/is-prop-valid/src/props.js

**Comment by bnert** [comment]
Hey @dvingo! Thanks so much for addressing this and for the extra information and for the code snippets, they are really helpful. 🙂🤘
